version: '3.8'

networks:
    web:
      external: true
      driver:  bridge



services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  app:
    build: 
      context: .
      shm_size: 2gb
    shm_size: 2gb
    tty: true
    stdin_open: true
    container_name: app
    networks:
            - web
    volumes:
      - ./app:/app
    # command: sh -c "pip install requests-html"
    command: sh -c "python bot.py"
    depends_on:
      - mongo
